package io.github.jbburns.manyfold.jdbc.internal.proxy;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import io.github.jbburns.manyfold.jdbc.ManyfoldException;
import io.github.jbburns.manyfold.jdbc.support.H2Pair;
import io.github.jbburns.manyfold.jdbc.support.MockedPair;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class StatementHandlerTest {

  private H2Pair dbs;
  private MockedPair mocks;

  @BeforeEach
  void setUp() throws SQLException {
    dbs = new H2Pair();
    mocks = new MockedPair();
  }

  @AfterEach
  void tearDown() throws SQLException {
    mocks.close();
    dbs.close();
  }

  private Connection h2Writable() throws SQLException {
    return DriverManager.getConnection(dbs.manyfoldUrl("readOnly=false"));
  }

  private static List<String> rows(ResultSet rs) throws SQLException {
    List<String> rows = new ArrayList<>();
    while (rs.next()) {
      rows.add(rs.getString(1) + "=" + rs.getString(2));
    }
    return rows;
  }

  // ---- real H2 backends ------------------------------------------------------------------

  @Test
  void callableStatementRunsOnEveryBackendAndMergesTheResult() throws Exception {
    try (Connection conn = h2Writable();
        CallableStatement call = conn.prepareCall("CALL 1 + 1")) {
      assertThat(call.execute()).isTrue();

      try (ResultSet rs = call.getResultSet()) {
        assertThat(rows(rs)).containsExactly("prod=2", "dev=2");
      }
      assertThat(call.getConnection()).isSameAs(conn);
    }
  }

  @Test
  void generatedKeysFromAnInsertAreMergedInBackendOrder() throws Exception {
    try (Connection conn = h2Writable();
        Statement s = conn.createStatement()) {
      s.execute("CREATE TABLE gen (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, v INT)");
      // Give the two backends different next identity values so the keys are distinguishable.
      try (Connection dev = dbs.dev();
          Statement d = dev.createStatement()) {
        d.execute("INSERT INTO gen(v) VALUES (0)");
        d.execute("INSERT INTO gen(v) VALUES (0)");
      }

      int updated =
          s.executeUpdate("INSERT INTO gen(v) VALUES (7)", Statement.RETURN_GENERATED_KEYS);

      assertThat(updated).isEqualTo(2);
      try (ResultSet keys = s.getGeneratedKeys()) {
        assertThat(rows(keys)).containsExactly("prod=1", "dev=3");
      }
    }
  }

  @Test
  void preparedStatementGeneratedKeysAreMergedToo() throws Exception {
    try (Connection conn = h2Writable();
        Statement s = conn.createStatement()) {
      s.execute("CREATE TABLE gen (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, v INT)");
      try (var ps =
          conn.prepareStatement("INSERT INTO gen(v) VALUES (?)", Statement.RETURN_GENERATED_KEYS)) {
        ps.setInt(1, 5);
        assertThat(ps.executeUpdate()).isEqualTo(2);

        try (ResultSet keys = ps.getGeneratedKeys()) {
          assertThat(rows(keys)).containsExactly("prod=1", "dev=1");
        }
      }
    }
  }

  @Test
  void executeLargeUpdateSumsTheCountsAsALong() throws Exception {
    try (Connection conn = h2Writable();
        Statement s = conn.createStatement()) {
      long updated = s.executeLargeUpdate("UPDATE orders SET amount = amount + 1");

      // prod has two orders and dev has one.
      assertThat(updated).isEqualTo(3L);
      assertThat(s.getLargeUpdateCount()).isEqualTo(3L);
      assertThat(s.getUpdateCount()).isEqualTo(3);
      assertThat(s.getResultSet()).isNull();
    }
  }

  @Test
  void updateCountIsMinusOneAfterAQuery() throws Exception {
    try (Connection conn = h2Writable();
        Statement s = conn.createStatement()) {
      assertThat(s.execute("SELECT id FROM orders")).isTrue();

      assertThat(s.getUpdateCount()).isEqualTo(-1);
      assertThat(s.getLargeUpdateCount()).isEqualTo(-1L);
      assertThat(s.getMoreResults()).isFalse();
    }
  }

  // ---- mock backends ---------------------------------------------------------------------

  @Test
  void executeFailsWhenBackendsDisagreeOnTheOutcome() throws Exception {
    when(mocks.statementA.execute("SELECT 1")).thenReturn(true);
    when(mocks.statementB.execute("SELECT 1")).thenReturn(false);

    try (Connection conn = mocks.open();
        Statement s = conn.createStatement()) {
      assertThatThrownBy(() -> s.execute("SELECT 1"))
          .isInstanceOf(ManyfoldException.class)
          .hasMessage(
              "Backends disagree on the outcome of execute: 'a' returned true but 'b' returned false");
    }
  }

  @Test
  void executeAgreementReturnsTheSharedOutcome() throws Exception {
    when(mocks.statementA.execute("SELECT 1")).thenReturn(false);
    when(mocks.statementB.execute("SELECT 1")).thenReturn(false);

    try (Connection conn = mocks.open();
        Statement s = conn.createStatement()) {
      assertThat(s.execute("SELECT 1")).isFalse();
    }
  }

  @Test
  void getMoreResultsFailsWhenBackendsDisagree() throws Exception {
    when(mocks.statementA.getMoreResults()).thenReturn(false);
    when(mocks.statementB.getMoreResults()).thenReturn(true);

    try (Connection conn = mocks.open();
        Statement s = conn.createStatement()) {
      assertThatThrownBy(s::getMoreResults)
          .isInstanceOf(ManyfoldException.class)
          .hasMessageStartingWith("Backends disagree on the outcome of getMoreResults");
    }
  }

  @Test
  void aBackendWithoutAResultSetWhenThePrimaryHasOneIsAnError() throws Exception {
    ResultSet first = mock(ResultSet.class);
    when(mocks.statementA.getResultSet()).thenReturn(first);
    when(mocks.statementB.getResultSet()).thenReturn(null);

    try (Connection conn = mocks.open();
        Statement s = conn.createStatement()) {
      assertThatThrownBy(s::getResultSet)
          .isInstanceOf(ManyfoldException.class)
          .hasMessage("Backend 'b' produced no result set for getResultSet while 'a' did");
      verify(first).close();
    }
  }

  @Test
  void updateCountUsesThePrimaryToDecideWhetherThereIsOne() throws Exception {
    when(mocks.statementA.getUpdateCount()).thenReturn(-1);
    when(mocks.statementB.getUpdateCount()).thenReturn(4);

    try (Connection conn = mocks.open();
        Statement s = conn.createStatement()) {
      assertThat(s.getUpdateCount()).isEqualTo(-1);
    }
  }

  @Test
  void batchResultsOfDifferentLengthAreAnError() throws Exception {
    when(mocks.statementA.executeBatch()).thenReturn(new int[] {1, 1});
    when(mocks.statementB.executeBatch()).thenReturn(new int[] {1});

    try (Connection conn = mocks.open("readOnly=false");
        Statement s = conn.createStatement()) {
      s.addBatch("INSERT INTO t VALUES (1)");
      s.addBatch("INSERT INTO t VALUES (2)");

      assertThatThrownBy(s::executeBatch)
          .isInstanceOf(ManyfoldException.class)
          .hasMessage("Backend 'b' returned 1 batch results but 'a' returned 2");
    }
  }

  @Test
  void largeBatchResultsOfDifferentLengthAreAnError() throws Exception {
    when(mocks.statementA.executeLargeBatch()).thenReturn(new long[] {1L});
    when(mocks.statementB.executeLargeBatch()).thenReturn(new long[] {1L, 1L, 1L});

    try (Connection conn = mocks.open("readOnly=false");
        Statement s = conn.createStatement()) {
      assertThatThrownBy(s::executeLargeBatch)
          .isInstanceOf(ManyfoldException.class)
          .hasMessage("Backend 'b' returned 3 batch results but 'a' returned 1");
    }
  }

  @Test
  void batchCountsAreSummedAndKeepTheJdbcSentinels() throws Exception {
    int noInfo = Statement.SUCCESS_NO_INFO;
    int failed = Statement.EXECUTE_FAILED;
    when(mocks.statementA.executeBatch()).thenReturn(new int[] {1, noInfo, 3, failed, noInfo, 6});
    when(mocks.statementB.executeBatch()).thenReturn(new int[] {2, 5, failed, 4, failed, noInfo});

    try (Connection conn = mocks.open("readOnly=false");
        Statement s = conn.createStatement()) {
      // A count plus a sentinel is the sentinel; two sentinels give the more severe,
      // EXECUTE_FAILED.
      assertThat(s.executeBatch()).containsExactly(3, noInfo, failed, failed, failed, noInfo);
    }
  }

  @Test
  void largeBatchCountsAreSummedAndKeepTheJdbcSentinels() throws Exception {
    long noInfo = Statement.SUCCESS_NO_INFO;
    long failed = Statement.EXECUTE_FAILED;
    when(mocks.statementA.executeLargeBatch())
        .thenReturn(new long[] {1L, noInfo, 3L, failed, noInfo, 6_000_000_000L});
    when(mocks.statementB.executeLargeBatch())
        .thenReturn(new long[] {2L, 5L, failed, 4L, failed, 6_000_000_000L});

    try (Connection conn = mocks.open("readOnly=false");
        Statement s = conn.createStatement()) {
      assertThat(s.executeLargeBatch())
          .containsExactly(3L, noInfo, failed, failed, failed, 12_000_000_000L);
    }
  }
}
