package io.github.jbburns.manyfold.jdbc.internal.proxy;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.ArgumentMatchers.same;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;

import io.github.jbburns.manyfold.jdbc.ManyfoldException;
import io.github.jbburns.manyfold.jdbc.support.H2Pair;
import io.github.jbburns.manyfold.jdbc.support.MockedPair;
import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.Reader;
import java.io.StringReader;
import java.nio.charset.StandardCharsets;
import java.sql.BatchUpdateException;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicReference;
import org.assertj.core.api.ThrowableAssert.ThrowingCallable;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.mockito.stubbing.Answer;

class StatementHandlerTest {

  private H2Pair dbs;
  private MockedPair mocks;

  @BeforeEach
  void setUp() throws SQLException {
    dbs = new H2Pair();
    mocks = new MockedPair();
  }

  @AfterEach
  void tearDown() throws SQLException {
    mocks.close();
    dbs.close();
  }

  private Connection h2Writable() throws SQLException {
    return DriverManager.getConnection(dbs.manyfoldUrl("readOnly=false"));
  }

  private static List<String> rows(ResultSet rs) throws SQLException {
    List<String> rows = new ArrayList<>();
    while (rs.next()) {
      rows.add(rs.getString(1) + "=" + rs.getString(2));
    }
    return rows;
  }

  // ---- real H2 backends ------------------------------------------------------------------

  @Test
  void callableStatementRunsOnEveryBackendAndMergesTheResult() throws Exception {
    try (Connection conn = h2Writable();
        CallableStatement call = conn.prepareCall("CALL 1 + 1")) {
      assertThat(call.execute()).isTrue();

      try (ResultSet rs = call.getResultSet()) {
        assertThat(rows(rs)).containsExactly("prod=2", "dev=2");
      }
      assertThat(call.getConnection()).isSameAs(conn);
    }
  }

  @Test
  void generatedKeysFromAnInsertAreMergedInBackendOrder() throws Exception {
    try (Connection conn = h2Writable();
        Statement s = conn.createStatement()) {
      s.execute("CREATE TABLE gen (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, v INT)");
      // Give the two backends different next identity values so the keys are distinguishable.
      try (Connection dev = dbs.dev();
          Statement d = dev.createStatement()) {
        d.execute("INSERT INTO gen(v) VALUES (0)");
        d.execute("INSERT INTO gen(v) VALUES (0)");
      }

      int updated =
          s.executeUpdate("INSERT INTO gen(v) VALUES (7)", Statement.RETURN_GENERATED_KEYS);

      assertThat(updated).isEqualTo(2);
      try (ResultSet keys = s.getGeneratedKeys()) {
        assertThat(rows(keys)).containsExactly("prod=1", "dev=3");
      }
    }
  }

  @Test
  void preparedStatementGeneratedKeysAreMergedToo() throws Exception {
    try (Connection conn = h2Writable();
        Statement s = conn.createStatement()) {
      s.execute("CREATE TABLE gen (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, v INT)");
      try (var ps =
          conn.prepareStatement("INSERT INTO gen(v) VALUES (?)", Statement.RETURN_GENERATED_KEYS)) {
        ps.setInt(1, 5);
        assertThat(ps.executeUpdate()).isEqualTo(2);

        try (ResultSet keys = ps.getGeneratedKeys()) {
          assertThat(rows(keys)).containsExactly("prod=1", "dev=1");
        }
      }
    }
  }

  @Test
  void executeLargeUpdateSumsTheCountsAsALong() throws Exception {
    try (Connection conn = h2Writable();
        Statement s = conn.createStatement()) {
      long updated = s.executeLargeUpdate("UPDATE orders SET amount = amount + 1");

      // prod has two orders and dev has one.
      assertThat(updated).isEqualTo(3L);
      assertThat(s.getLargeUpdateCount()).isEqualTo(3L);
      assertThat(s.getUpdateCount()).isEqualTo(3);
      assertThat(s.getResultSet()).isNull();
    }
  }

  @Test
  void updateCountIsMinusOneAfterAQuery() throws Exception {
    try (Connection conn = h2Writable();
        Statement s = conn.createStatement()) {
      assertThat(s.execute("SELECT id FROM orders")).isTrue();

      assertThat(s.getUpdateCount()).isEqualTo(-1);
      assertThat(s.getLargeUpdateCount()).isEqualTo(-1L);
      assertThat(s.getMoreResults()).isFalse();
    }
  }

  // ---- mock backends ---------------------------------------------------------------------

  @Test
  void executeFailsWhenBackendsDisagreeOnTheOutcome() throws Exception {
    when(mocks.statementA.execute("SELECT 1")).thenReturn(true);
    when(mocks.statementB.execute("SELECT 1")).thenReturn(false);

    try (Connection conn = mocks.open();
        Statement s = conn.createStatement()) {
      assertThatThrownBy(() -> s.execute("SELECT 1"))
          .isInstanceOf(ManyfoldException.class)
          .hasMessage(
              "Backends disagree on the outcome of execute: 'a' returned true but 'b' returned false");
    }
  }

  @Test
  void executeAgreementReturnsTheSharedOutcome() throws Exception {
    when(mocks.statementA.execute("SELECT 1")).thenReturn(false);
    when(mocks.statementB.execute("SELECT 1")).thenReturn(false);

    try (Connection conn = mocks.open();
        Statement s = conn.createStatement()) {
      assertThat(s.execute("SELECT 1")).isFalse();
    }
  }

  @Test
  void getMoreResultsFailsWhenBackendsDisagree() throws Exception {
    when(mocks.statementA.getMoreResults()).thenReturn(false);
    when(mocks.statementB.getMoreResults()).thenReturn(true);

    try (Connection conn = mocks.open();
        Statement s = conn.createStatement()) {
      assertThatThrownBy(s::getMoreResults)
          .isInstanceOf(ManyfoldException.class)
          .hasMessageStartingWith("Backends disagree on the outcome of getMoreResults");
    }
  }

  @Test
  void aBackendWithoutAResultSetWhenThePrimaryHasOneIsAnError() throws Exception {
    ResultSet first = mock(ResultSet.class);
    when(mocks.statementA.getResultSet()).thenReturn(first);
    when(mocks.statementB.getResultSet()).thenReturn(null);

    try (Connection conn = mocks.open();
        Statement s = conn.createStatement()) {
      assertThatThrownBy(s::getResultSet)
          .isInstanceOf(ManyfoldException.class)
          .hasMessage("Backend 'b' produced no result set for getResultSet while 'a' did");
      verify(first).close();
    }
  }

  @Test
  void updateCountUsesThePrimaryToDecideWhetherThereIsOne() throws Exception {
    when(mocks.statementA.getUpdateCount()).thenReturn(-1);
    when(mocks.statementB.getUpdateCount()).thenReturn(4);

    try (Connection conn = mocks.open();
        Statement s = conn.createStatement()) {
      assertThat(s.getUpdateCount()).isEqualTo(-1);
    }
  }

  @Test
  void batchResultsOfDifferentLengthAreAnError() throws Exception {
    when(mocks.statementA.executeBatch()).thenReturn(new int[] {1, 1});
    when(mocks.statementB.executeBatch()).thenReturn(new int[] {1});

    try (Connection conn = mocks.open("readOnly=false");
        Statement s = conn.createStatement()) {
      s.addBatch("INSERT INTO t VALUES (1)");
      s.addBatch("INSERT INTO t VALUES (2)");

      assertThatThrownBy(s::executeBatch)
          .isInstanceOf(ManyfoldException.class)
          .hasMessage("Backend 'b' returned 1 batch results but 'a' returned 2");
    }
  }

  @Test
  void largeBatchResultsOfDifferentLengthAreAnError() throws Exception {
    when(mocks.statementA.executeLargeBatch()).thenReturn(new long[] {1L});
    when(mocks.statementB.executeLargeBatch()).thenReturn(new long[] {1L, 1L, 1L});

    try (Connection conn = mocks.open("readOnly=false");
        Statement s = conn.createStatement()) {
      assertThatThrownBy(s::executeLargeBatch)
          .isInstanceOf(ManyfoldException.class)
          .hasMessage("Backend 'b' returned 3 batch results but 'a' returned 1");
    }
  }

  @Test
  void batchCountsAreSummedAndKeepTheJdbcSentinels() throws Exception {
    int noInfo = Statement.SUCCESS_NO_INFO;
    int failed = Statement.EXECUTE_FAILED;
    when(mocks.statementA.executeBatch()).thenReturn(new int[] {1, noInfo, 3, failed, noInfo, 6});
    when(mocks.statementB.executeBatch()).thenReturn(new int[] {2, 5, failed, 4, failed, noInfo});

    try (Connection conn = mocks.open("readOnly=false");
        Statement s = conn.createStatement()) {
      // A count plus a sentinel is the sentinel; two sentinels give the more severe,
      // EXECUTE_FAILED.
      assertThat(s.executeBatch()).containsExactly(3, noInfo, failed, failed, failed, noInfo);
    }
  }

  @Test
  void largeBatchCountsAreSummedAndKeepTheJdbcSentinels() throws Exception {
    long noInfo = Statement.SUCCESS_NO_INFO;
    long failed = Statement.EXECUTE_FAILED;
    when(mocks.statementA.executeLargeBatch())
        .thenReturn(new long[] {1L, noInfo, 3L, failed, noInfo, 6_000_000_000L});
    when(mocks.statementB.executeLargeBatch())
        .thenReturn(new long[] {2L, 5L, failed, 4L, failed, 6_000_000_000L});

    try (Connection conn = mocks.open("readOnly=false");
        Statement s = conn.createStatement()) {
      assertThat(s.executeLargeBatch())
          .containsExactly(3L, noInfo, failed, failed, failed, 12_000_000_000L);
    }
  }

  @Test
  void getUpdateCountIsMinusOneWhenAnyBackendReportsMinusOne() throws Exception {
    when(mocks.statementA.getUpdateCount()).thenReturn(3);
    when(mocks.statementB.getUpdateCount()).thenReturn(-1);
    when(mocks.statementA.getLargeUpdateCount()).thenReturn(3L);
    when(mocks.statementB.getLargeUpdateCount()).thenReturn(-1L);

    try (Connection conn = mocks.open();
        Statement s = conn.createStatement()) {
      assertThat(s.getUpdateCount()).isEqualTo(-1);
      assertThat(s.getLargeUpdateCount()).isEqualTo(-1L);
    }
  }

  @Test
  void anIntUpdateCountOverflowIsASqlExceptionNotAnArithmeticException() throws Exception {
    when(mocks.statementA.executeUpdate("UPDATE t SET x = 1")).thenReturn(Integer.MAX_VALUE);
    when(mocks.statementB.executeUpdate("UPDATE t SET x = 1")).thenReturn(1);
    when(mocks.statementA.executeLargeUpdate("UPDATE t SET x = 1")).thenReturn(Long.MAX_VALUE);
    when(mocks.statementB.executeLargeUpdate("UPDATE t SET x = 1")).thenReturn(1L);

    try (Connection conn = mocks.open("readOnly=false");
        Statement s = conn.createStatement()) {
      assertThatThrownBy(() -> s.executeUpdate("UPDATE t SET x = 1"))
          .isInstanceOf(SQLException.class)
          .hasMessageContaining("add up to more than an int")
          .hasCauseInstanceOf(ArithmeticException.class);
      assertThatThrownBy(() -> s.executeLargeUpdate("UPDATE t SET x = 1"))
          .isInstanceOf(SQLException.class)
          .hasMessageContaining("add up to more than a long");
    }
  }

  @Test
  void aNullSqlStringIsRefusedInReadOnlyModeInsteadOfSkippingTheGuard() throws Exception {
    try (Connection conn = mocks.open();
        Statement s = conn.createStatement()) {
      for (ThrowingCallable call :
          new ThrowingCallable[] {
            () -> s.executeQuery(null),
            () -> s.execute(null),
            () -> s.executeUpdate(null),
            () -> s.addBatch(null)
          }) {
        assertThatThrownBy(call)
            .isInstanceOf(ManyfoldException.class)
            .hasMessageStartingWith("Refused in read-only mode: statement is null")
            .satisfies(
                e ->
                    assertThat(((SQLException) e).getSQLState())
                        .isEqualTo(ManyfoldException.STATE_READ_ONLY));
      }
      verifyNoInteractions(mocks.statementA, mocks.statementB);
    }
  }

  @Test
  void aBatchUpdateExceptionSurvivesWithItsCounts() throws Exception {
    BatchUpdateException vendor =
        new BatchUpdateException(
            "row 2 failed", "23505", 7, new int[] {1, Statement.EXECUTE_FAILED});
    when(mocks.statementB.executeBatch()).thenThrow(vendor);
    when(mocks.statementA.executeBatch()).thenReturn(new int[] {1, 1});

    try (Connection conn = mocks.open("readOnly=false");
        Statement s = conn.createStatement()) {
      s.addBatch("INSERT INTO t VALUES (1)");
      s.addBatch("INSERT INTO t VALUES (1)");

      assertThatThrownBy(s::executeBatch)
          .isExactlyInstanceOf(BatchUpdateException.class)
          .hasMessage("Backend 'b' failed: row 2 failed")
          .hasCause(vendor)
          .satisfies(
              e -> {
                BatchUpdateException batch = (BatchUpdateException) e;
                assertThat(batch.getUpdateCounts()).containsExactly(1, Statement.EXECUTE_FAILED);
                assertThat(batch.getSQLState()).isEqualTo("23505");
                assertThat(batch.getErrorCode()).isEqualTo(7);
              });
    }
  }

  @Test
  void streamingSettersGiveEveryBackendItsOwnCopyOfTheData() throws Exception {
    try (Connection prod = dbs.prod();
        Connection dev = dbs.dev()) {
      for (Connection direct : new Connection[] {prod, dev}) {
        try (Statement s = direct.createStatement()) {
          s.execute("CREATE TABLE streams (id INT, txt CLOB, bin BLOB, ascii CLOB)");
        }
      }
    }
    String text = "h\u00e9llo w\u00f6rld " + "x".repeat(20_000);
    byte[] bytes = new byte[50_000];
    for (int i = 0; i < bytes.length; i++) {
      bytes[i] = (byte) i;
    }
    try (Connection conn = h2Writable();
        PreparedStatement ps = conn.prepareStatement("INSERT INTO streams VALUES (?, ?, ?, ?)")) {
      ps.setInt(1, 1);
      ps.setCharacterStream(2, new StringReader(text));
      ps.setBinaryStream(3, new ByteArrayInputStream(bytes));
      ps.setAsciiStream(4, new ByteArrayInputStream("ascii".getBytes(StandardCharsets.US_ASCII)));
      assertThat(ps.executeUpdate()).isEqualTo(2);

      ps.setInt(1, 2);
      ps.setCharacterStream(2, new StringReader(text), 5);
      ps.setBinaryStream(3, new ByteArrayInputStream(bytes), 10L);
      ps.setNCharacterStream(4, new StringReader("nchars"));
      assertThat(ps.executeUpdate()).isEqualTo(2);

      ps.setInt(1, 3);
      ps.setClob(2, new StringReader("clob"));
      ps.setBlob(3, new ByteArrayInputStream(new byte[] {1, 2, 3}));
      ps.setNClob(4, new StringReader("nclob"), 5L);
      assertThat(ps.executeUpdate()).isEqualTo(2);
    }

    for (String url : new String[] {dbs.prodUrl, dbs.devUrl}) {
      try (Connection direct = DriverManager.getConnection(url);
          Statement s = direct.createStatement();
          ResultSet rs = s.executeQuery("SELECT id, txt, bin, ascii FROM streams ORDER BY id")) {
        assertThat(rs.next()).isTrue();
        assertThat(rs.getString(2)).as(url).isEqualTo(text);
        assertThat(rs.getBytes(3)).as(url).isEqualTo(bytes);
        assertThat(rs.getString(4)).as(url).isEqualTo("ascii");
        assertThat(rs.next()).isTrue();
        assertThat(rs.getString(2)).as(url).isEqualTo(text.substring(0, 5));
        assertThat(rs.getBytes(3)).as(url).isEqualTo(Arrays.copyOf(bytes, 10));
        assertThat(rs.getString(4)).as(url).isEqualTo("nchars");
        assertThat(rs.next()).isTrue();
        assertThat(rs.getString(2)).as(url).isEqualTo("clob");
        assertThat(rs.getBytes(3)).as(url).isEqualTo(new byte[] {1, 2, 3});
        assertThat(rs.getString(4)).as(url).isEqualTo("nclob");
        assertThat(rs.next()).isFalse();
      }
    }
  }

  @Test
  void interruptingAThreadBlockedInExecuteQueryCancelsEveryBackendStatement() throws Exception {
    CountDownLatch started = new CountDownLatch(2);
    CountDownLatch never = new CountDownLatch(1);
    Answer<ResultSet> blocking =
        invocation -> {
          started.countDown();
          try {
            never.await();
          } catch (InterruptedException e) {
            throw new SQLException("interrupted", e);
          }
          return null;
        };
    when(mocks.statementA.executeQuery("SELECT 1")).thenAnswer(blocking);
    when(mocks.statementB.executeQuery("SELECT 1")).thenAnswer(blocking);
    AtomicReference<Throwable> thrown = new AtomicReference<>();
    try (Connection conn = mocks.open()) {
      Statement s = conn.createStatement();
      Thread caller =
          new Thread(
              () -> {
                try {
                  s.executeQuery("SELECT 1");
                } catch (Throwable t) {
                  thrown.set(t);
                }
              });
      caller.start();
      assertThat(started.await(5, TimeUnit.SECONDS)).isTrue();

      caller.interrupt();
      caller.join(5000);

      assertThat(caller.isAlive()).isFalse();
      assertThat(thrown.get())
          .isInstanceOf(SQLException.class)
          .hasMessageContaining("Interrupted while waiting");
      verify(mocks.statementA).cancel();
      verify(mocks.statementB).cancel();
    }
  }

  @Test
  void aCancelThatFailsDuringAnInterruptDoesNotHideTheInterrupt() throws Exception {
    CountDownLatch started = new CountDownLatch(2);
    CountDownLatch never = new CountDownLatch(1);
    Answer<ResultSet> blocking =
        invocation -> {
          started.countDown();
          try {
            never.await();
          } catch (InterruptedException e) {
            throw new SQLException("interrupted", e);
          }
          return null;
        };
    when(mocks.statementA.executeQuery("SELECT 1")).thenAnswer(blocking);
    when(mocks.statementB.executeQuery("SELECT 1")).thenAnswer(blocking);
    doThrow(new SQLException("cannot cancel")).when(mocks.statementA).cancel();
    AtomicReference<Throwable> thrown = new AtomicReference<>();
    try (Connection conn = mocks.open()) {
      Statement s = conn.createStatement();
      Thread caller =
          new Thread(
              () -> {
                try {
                  s.executeQuery("SELECT 1");
                } catch (Throwable t) {
                  thrown.set(t);
                }
              });
      caller.start();
      assertThat(started.await(5, TimeUnit.SECONDS)).isTrue();

      caller.interrupt();
      caller.join(5000);

      assertThat(thrown.get()).hasMessageContaining("Interrupted while waiting");
      verify(mocks.statementB).cancel();
    }
  }

  @Test
  void aFailingBackendClosesTheHealthyBackendsResultSet() throws Exception {
    ResultSet healthy = mock(ResultSet.class);
    when(mocks.statementA.executeQuery("SELECT 1")).thenReturn(healthy);
    when(mocks.statementB.executeQuery("SELECT 1")).thenThrow(new SQLException("down", "08006"));

    try (Connection conn = mocks.open();
        Statement s = conn.createStatement()) {
      assertThatThrownBy(() -> s.executeQuery("SELECT 1"))
          .isInstanceOf(SQLException.class)
          .hasMessage("Backend 'b' failed: down");
      verify(healthy).close();
    }
  }

  private static String read(InputStream in) throws IOException {
    return new String(in.readAllBytes(), StandardCharsets.ISO_8859_1);
  }

  @Test
  void withOneBackendStreamsAndReadersGoStraightThrough() throws Exception {
    PreparedStatement ps = mock(PreparedStatement.class);
    when(mocks.a.prepareStatement("INSERT INTO t VALUES (?)")).thenReturn(ps);
    InputStream in = new ByteArrayInputStream(new byte[] {1, 2, 3});
    Reader reader = new StringReader("chars");
    try (Connection conn = mocks.openFirstOnly("readOnly=false");
        PreparedStatement p = conn.prepareStatement("INSERT INTO t VALUES (?)")) {
      p.setBinaryStream(1, in);
      p.setBinaryStream(1, in, 2L);
      p.setCharacterStream(2, reader);
      p.setCharacterStream(2, reader, 3);

      verify(ps).setBinaryStream(eq(1), same(in));
      verify(ps).setBinaryStream(eq(1), same(in), eq(2L));
      verify(ps).setCharacterStream(eq(2), same(reader));
      verify(ps).setCharacterStream(eq(2), same(reader), eq(3));
      // Untouched: nothing was read on the way through.
      assertThat(in.available()).isEqualTo(3);
      assertThat((char) reader.read()).isEqualTo('c');
    }
  }

  @Test
  void withSeveralBackendsALengthLimitsHowMuchIsReadFromTheSource() throws Exception {
    PreparedStatement psA = mock(PreparedStatement.class);
    PreparedStatement psB = mock(PreparedStatement.class);
    when(mocks.a.prepareStatement("INSERT INTO t VALUES (?)")).thenReturn(psA);
    when(mocks.b.prepareStatement("INSERT INTO t VALUES (?)")).thenReturn(psB);
    byte[] bytes = new byte[100];
    for (int i = 0; i < bytes.length; i++) {
      bytes[i] = (byte) ('a' + i % 26);
    }
    InputStream in = new ByteArrayInputStream(bytes);
    Reader reader = new StringReader("abcdefghij");
    Reader shortReader = new StringReader("xy");

    try (Connection conn = mocks.open("readOnly=false");
        PreparedStatement p = conn.prepareStatement("INSERT INTO t VALUES (?)")) {
      p.setBinaryStream(1, in, 10L);
      p.setCharacterStream(2, reader, 4);
      p.setCharacterStream(3, shortReader, 50L);
    }

    for (PreparedStatement ps : new PreparedStatement[] {psA, psB}) {
      ArgumentCaptor<InputStream> stream = ArgumentCaptor.forClass(InputStream.class);
      verify(ps).setBinaryStream(eq(1), stream.capture(), eq(10L));
      assertThat(read(stream.getValue())).isEqualTo("abcdefghij");
      ArgumentCaptor<Reader> chars = ArgumentCaptor.forClass(Reader.class);
      verify(ps).setCharacterStream(eq(2), chars.capture(), eq(4));
      assertThat(chars.getValue()).isNotSameAs(reader);
      assertThat(new BufferedReader(chars.getValue()).readLine()).isEqualTo("abcd");
      ArgumentCaptor<Reader> shorter = ArgumentCaptor.forClass(Reader.class);
      verify(ps).setCharacterStream(eq(3), shorter.capture(), eq(50L));
      assertThat(new BufferedReader(shorter.getValue()).readLine()).isEqualTo("xy");
    }
    // Only the limited amount was consumed from the caller's stream and reader.
    assertThat(in.available()).isEqualTo(90);
    assertThat((char) reader.read()).isEqualTo('e');
  }
}
